---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: ${PLATFORM_NAME}
    image_name: ${AMI_NAME}
    image_owner: ${AMI_OWNER_ID}
    instance_type: ${INSTANCE_TYPE}
    keypair_name: ${KEYPAIR_NAME}
    security_group_name: ${SECURITY_GROUP_NAME}
    security_group_rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: '0.0.0.0/0'
    security_group_rules_egress:
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip: '0.0.0.0/0'
    ssh_port: 22
    ssh_user: ${ANSIBLE_USER}
    tag_name: ${TAG_NAME}
    tag_created_by: ${CREATED_BY}
    volumes:
      - device_name: /dev/sda1
        ebs:
          delete_on_termination: yes
          volume_type: 'gp3'
    vpc_subnet_id: ${VPC_SUBNET_ID}
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      verbosity: 0
  connection_options:
    ansible_user: ${ANSIBLE_USER}
    wp_backup_data_path: '/tmp/wp-install'
    wp_backup_data_owner: 'apache'
    wp_backup_data_group: 'apache'
    wp_installed_path: '/var/www/html/wordpress'
    wp_db_dump_data_sql: 'wp.sql'
  env:
    MOLECULE_DEBUG: true
  log: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - verify
    - cleanup
    - destroy
